- src/components/Uploader.js
> Fix checking files on change widget in Uploader

- package.json
> setup release-it

- package.json
> setup git hooks with husky

- README.md
> Use regular comment style in usage example

- package.json
- rollup.config.js
> Add preset env

- package.json
> Update widget version

- package.json
> fix(types): fix paths to *.d.ts  files

- .github/workflows/shipjs-manual-prepare.yml
- .github/workflows/shipjs-trigger.yml
- .npmrc
- package-lock.json
- ship.config.js
I remove `.npmrc` because npm auth don't work in actions with that file in repo 😔
> chore: setup github actions

- .github/workflows/shipjs-manual-prepare.yml
- .github/workflows/shipjs-schedule-prepare.yml
- .github/workflows/shipjs-trigger.yml
- package-lock.json
* add schedule action
* use autogenerated secret `GITHUB_TOKEN` in all actions
> chore: improve github actions

- dummy/app.js
- dummy/crop.js
- dummy/effect.js
- package-lock.json
- package.json
- src/index.js
- types/index.d.ts
> fix(types): add types for effects tab translations

- src/uploader.js
> fix: don't prefix input name and id attributes with `data`

- .github/workflows/shipjs-manual-prepare.yml
- .github/workflows/shipjs-schedule-prepare.yml
- .github/workflows/shipjs-trigger.yml
- ship.config.js
Like
https://github.com/uploadcare/uploadcare-upload-client/pull/239
> chore: update shipjs config

- src/index.js
> fix: enable tree shaking with pure notation

- package-lock.json
> chore(deps): fixed vulnerabilities

- types/index.d.ts
- types/test.tsx
sync ts types with new features
> fix(types): add type for tabsCss prop

- .github/renovate.json
- ship.config.js
> chore: new core maintainer

- __setups__/scroll.js
- dummy/crop.js
- dummy/default-panel.js
- dummy/effect.js
- package-lock.json
- package.json
Mock methods that throw errors in test
> test: mock canvas and scrollTo methods

- README.md
- dummy/dialog-callbacks.js
- dummy/dynamic-locales.js
- types/index.d.ts
- types/test.tsx
> fix(types): improve `onFileSelect` callback typings

- types/index.d.ts
> fix(types): add crop to FileInfo

- types/index.d.ts
- types/test.tsx
> fix(types): fix preloader type

- package-lock.json
- package.json
- types/index.d.ts
> fix: bump widget version

- README.md
- dummy/default-panel.js
- package.json
- src/dialog.js
- src/hooks/use-deep-memo.js
- src/index.js
- src/uploader.js
- test/index.js
- test/locale.js
- types/index.d.ts
- types/test.tsx
- types/tsconfig.json
> feat: `Panel` component

- README.md
- package.json
> fix: add `exports` field to the package.json

- rollup.config.js
Fixes https://github.com/uploadcare/react-widget/issues/342
> fix: add extension to uploadcare-widget import

- README.md
- package-lock.json
- package.json
- src/uploader.js
- test/index.js
- types/index.d.ts
Fixes https://github.com/uploadcare/react-widget/issues/346
> feat(Widget): add `widgetApiRef.setValue` method

- README.md
- package-lock.json
- package.json
- src/dialog.js
- src/uploader.js
- types/index.d.ts
- types/test.tsx
Fixes both https://github.com/uploadcare/react-widget/issues/370 and https://github.com/uploadcare/react-widget/issues/369
> Export missing types

- package-lock.json
- package.json
- rollup.config.js
> chore: separate typing files for CJS and ESM modules
